name: Deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - prod
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Checkout Git Branch
        uses: actions/checkout@v3
        with:
          ref: 'prod'
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
