name: Deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - prod
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Checkout Git Branch
        uses: actions/checkout@v3
        with:
          ref: 'prod'
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Upload to blob storage
        uses: azure/CLI@v1
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        with:
          inlineScript: |
              az storage blob upload-batch \
                --account-name $AZURE_STORAGE_ACCOUNT_NAME \
                --auth-mode key \
                --destination '$AZURE_STORAGE_CONTAINER' \
                --source dist
      - name: logout
        run: |
              az logout
        if: always()